SELECT
    dm.SESSION_ID,
    dm.PATIENT_ID,
    dm.PROTOCOL_ID,
    dm.GAME_MODE,
    dm.SECONDS_FROM_START,
    dm.PARAMETER_KEY,
    CAST(dm.PARAMETER_VALUE AS FLOAT) AS PARAMETER_VALUE,
    pe.PARAMETER_KEY AS PERFORMANCE_KEY,
    CAST(pe.PARAMETER_VALUE AS FLOAT) AS PERFORMANCE_VALUE
FROM difficulty_modulators_{rgs_mode} dm
JOIN performance_estimators_{rgs_mode} pe
ON dm.SESSION_ID = pe.SESSION_ID
AND dm.PATIENT_ID = pe.PATIENT_ID
AND dm.PROTOCOL_ID = pe.PROTOCOL_ID
AND dm.GAME_MODE = pe.GAME_MODE
AND dm.SECONDS_FROM_START = pe.SECONDS_FROM_START
WHERE dm.PATIENT_ID IN :patient_ids;