SELECT
    p.PROTOCOL_ID,
    p.NAME_KEY AS PROTOCOL_NAME,
    p.PROTOCOL_TYPE_ID,
    pt.PROTOCOL_TYPE AS PROTOCOL_TYPE_NAME
FROM protocol p
JOIN protocol_type pt ON p.PROTOCOL_TYPE_ID = pt.PROTOCOL_TYPE_ID
ORDER BY p.PROTOCOL_ID;
